### ISSUE TITLE
Error in source, does not compile

### ISSUE THREAD

**Issue by JacobSiegle** [Azure-Samples/media-services-v3-dotnet-tutorials#11]
https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials/blob/0d0449b60df8b7bd38c64b2c9a0c5ccea1ef40c5/AMSV3Tutorials/UploadEncodeAndStreamFiles/Program.cs#L87

outputAsset.Name doesn't exist. I'm assuming the file is out of sync with -

https://github.com/Azure-Samples/media-services-v3-dotnet-quickstarts/blob/master/AMSV3Quickstarts/EncodeAndStreamFiles/Program.cs

**Comment by Juliako** [comment]
@JacobSiegle , thank you so much for bringing it to my attention. I by mistake deleted
            // Output from the encoding Job must be written to an Asset, so let's create one
            Asset outputAsset = await CreateOutputAssetAsync(client, config.ResourceGroup, config.AccountName, outputAssetName);

**Comment by Juliako** [comment]
@JacobSiegle , thank you so much for bringing it to my attention. I by mistake deleted

    Asset outputAsset = await CreateOutputAssetAsync(client, config.ResourceGroup, config.AccountName, outputAssetName);
