### ISSUE TITLE
Unable to Verify Token JWT 

### ISSUE THREAD

**Issue by Yusebs23** [Azure-Samples/media-services-v3-dotnet-tutorials#12]
I have few problems about azure media services V3
I need to upload assets to the Azure portal, run the encode and then encrypt it. So far, everything is ok!!.
Now I have to write the code:
I set the content protection with TOKEN: Token Issuer, Token scope and primary key random.
Then:

        private static string Issuer = "https://sts.windows.net/";
        private static string Audience = "urn:testazuremediaservices";
        private static string key = "XXXXXX";

            string locator = "29a2988a-96fc-46f9-b12f-74060ca9dac8"; (obtained by API call)
            string keyIdentifier = "e22675fc-f047-4953-ad2b-1176cbc7783a";(obtained by API call)
            var TokenSigningKey = Encoding.ASCII.GetBytes(key);

            string token = GetTokenAsync(Issuer, Audience, keyIdentifier, TokenSigningKey);
            
            string dashPath = await GetDASHStreamingUrlAsync(client, config.ResourceGroup, config.AccountName, locator);

            
            Console.WriteLine($"https://ampdemo.azureedge.net/?url={dashPath}&aes=true&aestoken=Bearer%3D{token}");
            Console.WriteLine();

private static string GetTokenAsync(string issuer, string audience, string keyIdentifier, byte[] tokenVerificationKey)
        {
            var tokenSigningKey = new SymmetricSecurityKey(tokenVerificationKey);

            SigningCredentials cred = new SigningCredentials(
                tokenSigningKey,
                // Use the  HmacSha256 and not the HmacSha256Signature option, or the token will not work!
                SecurityAlgorithms.HmacSha256,
                SecurityAlgorithms.Sha256Digest);

            JwtSecurityToken token = new JwtSecurityToken(
                issuer: issuer,
                audience: audience,
                //claims: claims,
                notBefore: DateTime.Now.AddMinutes(-5),
                expires: DateTime.Now.AddMinutes(60),
                signingCredentials: cred);

            JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();

            return handler.WriteToken(token);
        }

private static async Task<string> GetDASHStreamingUrlAsync(
            IAzureMediaServicesClient client,
            string resourceGroupName,
            string accountName,
            string locatorName)
        {
            const string DefaultStreamingEndpointName = "default";

            string dashPath = "";

            StreamingEndpoint streamingEndpoint = await client.StreamingEndpoints.GetAsync(resourceGroupName, accountName, DefaultStreamingEndpointName);

            if (streamingEndpoint != null)
            {
                if (streamingEndpoint.ResourceState != StreamingEndpointResourceState.Running)
                {
                    await client.StreamingEndpoints.StartAsync(resourceGroupName, accountName, DefaultStreamingEndpointName);
                }
            }

            ListPathsResponse paths = await client.StreamingLocators.ListPathsAsync(resourceGroupName, accountName, locatorName);

            foreach (StreamingPath path in paths.StreamingPaths)
            {
                UriBuilder uriBuilder = new UriBuilder();
                uriBuilder.Scheme = "https";
                uriBuilder.Host = streamingEndpoint.HostName;

                // Look for just the DASH path and generate a URL for the Azure Media Player to playback the content with the AES token to decrypt.
                // Note that the JWT token is set to expire in 1 hour. 
                if (path.StreamingProtocol == StreamingPolicyStreamingProtocol.Dash)
                {
                    uriBuilder.Path = path.Paths[0];

                    dashPath = uriBuilder.ToString();

                }
            }

            return dashPath;
        }

When I get the final link, AMP gives me the error 0x20500004. Can someone help me? Thank you

**Comment by willzhan** [comment]
The best way to troubleshoot the issue of JWT/STS, license service, player and DRM encryptor working together is to go in steps: first use a ContentKeyPolicyRestriction which is Open (instead of token restriction), make sure it works in this case end-to-end. It is easier to make this case work. Then change to token restriction in ContentKeyPolicyRestriction. Make sure the scope and issuer (and claims) match up exactly between JWT generator (STS) and what you set in ContentKeyPolicyRestriction.

This 2 step process allows you quickly zoom to the location where it goes wrong: ContentKeyPolicyRestriction and JWT generator matching up.

**Comment by xpouyat** [comment]
A common mistake is to forget to put the content key id in the claims....

**Comment by johndeu** [comment]
Closing issue as I believe William and Xavier have provided enough details
