### ISSUE TITLE
urn:microsoft:azure:mediaservices:maxuses

### ISSUE THREAD

**Issue by Brickhead** [Azure-Samples/media-services-v3-dotnet-tutorials#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Following the DRM guide:
https://docs.microsoft.com/en-gb/azure/media-services/latest/protect-with-drm#get-a-test-token

Adding claim "maxuses" doesn't seem to limit the times a token can be used when streaming an asset with AES-128 ClearKey, Is this only usable in DRM streams and not AES-128?

Added this Claim in JWT token:
new Claim("urn:microsoft:azure:mediaservices:maxuses", "1", ClaimValueTypes.Integer)

### Expected/desired behavior
>
Should only be able to use the token once?

### Versions
>
Azure.Management.Media 2.0.3

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Hello,
'maxuses' works for aes clear key.
The feature is deployed in US Central and US West Central regions only. Make sure you test in these regions.
https://docs.microsoft.com/en-us/azure/media-services/latest/release-notes

**Comment by xpouyat** [comment]
Which region are you using ? We may enable the feature in that region quicker if you need it.

**Comment by Brickhead** [comment]
Thanks for clarifying! 

That would be great, West Europe.

Maybe it could be added as a note in the examples as well as just in the release notes?
