### ISSUE TITLE
How to setup Media services v3 only for DRM license acquisition

### ISSUE THREAD

**Issue by Ross-cz** [Azure-Samples/media-services-v3-dotnet-tutorials#14]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
I checked the documentation multiple times, but I am not able to find any info regarding the DRM license acquisition model, when you need to process whole asset yourself without Azure.

Is there a table with some supported / unsupported scenarios?

Is it supported scenario to use only Azure license acquisition from whole Media services v3?

**Comment by Juliako** [comment]
Hi @Ross-cz , have you seen this section [custom-key-and-license-acquisition-url](https://docs.microsoft.com/en-us/azure/media-services/latest/content-protection-overview#custom-key-and-license-acquisition-url)?

**Comment by Ross-cz** [comment]
Hi Juliako, yes, but this allows you to set custom 3rd party key and license acquistion url instead of Azure one, but I want to use this service from Media services without the packaging.

Is it possible to use only license acquisition part of the Media services v3?

Thx for support,
R

**Comment by johndeu** [comment]
Not supported in v3 today - we only support usage when streaming from AMS packager.
