### ISSUE TITLE
Can't create a new AzureMediaServicesClient

### ISSUE THREAD

**Issue by TheAustinG** [Azure-Samples/media-services-v3-dotnet-tutorials#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Followed steps to connect to Media Services

### Any log messages given by the failure
> 

    Attempted to access an element as a type incompatible with the array
    

    at System.Collections.Generic.List`1.Add(T item)

    at Microsoft.Azure.Management.Media.AzureMediaServicesClient.Initialize()

    at Microsoft.Azure.Management.Media.AzureMediaServicesClient..ctor(Uri baseUri, ServiceClientCredentials credentials, DelegatingHandler[] handlers)

### Expected/desired behavior
> Successful connection to Media Services

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful
 I have followed the tutorial that is provided here. However, I keep getting the above error when trying to instantiate a new AzureMediaServicesClient. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Try with latest repo and SDK updates
