### ISSUE TITLE
ClientCredential is now obsolete.

### ISSUE THREAD

**Issue by rdurrance** [Azure-Samples/media-services-v3-dotnet-tutorials#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Use the videoEncode tutorial

### Any log messages given by the failure
>
'ClientCredential' is obsolete: 'Use ConfidentialClientApplicationBuilder.WithCertificate or WithClientSecret instead. See https://aka.ms/msal-net-3-breaking-changes
### Expected/desired behavior
>
Method that is not obsolete
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
VS 2019
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Updated repo with new Authentication methods
