### ISSUE TITLE
Build error during UploadEncodeAndStreamFiles

### ISSUE THREAD

**Issue by rachita2901** [Azure-Samples/media-services-v3-dotnet-tutorials#25]
I tried executing the UploadEncodeAndStreamFiles code as per the Microsoft documentation. I faced the following build error. 
I also followed along with the answers that faced the similar issue but no luck. I even downgraded and tried using .Net 2.0 but still the same error. 

Please help ASAP
![image](https://user-images.githubusercontent.com/49995220/129350950-06d61b3b-39c5-4706-bb69-63652e7f3dd7.png)

**Comment by Jim-Thompson-Cru** [comment]
I'm getting this build error:  'TokenType' does not exist in the current context ( which makes sense because it does not appear to be defined anywhere.

![image](https://user-images.githubusercontent.com/42070991/129455800-d6d91c63-4247-44c4-95c5-7bf7c4b605d0.png)

**Comment by Dredy** [comment]
Hi,
to resolve this issue add this row in the Program.cs file, after the "private const string ...." declarations

public static readonly string TokenType = "Bearer";

I fount this on the Authentication.cs file of the Common-Utils project

Hope it helps.

**Comment by xpouyat** [comment]
Thanks for the report! The issue came from some recent commits that broke the code. These commits have been removed.
