### ISSUE TITLE
Doesn't build when Microsoft.Azure.Management.Media is updated to v 5.0.0.0

### ISSUE THREAD

**Issue by sumitkm** [Azure-Samples/media-services-v3-dotnet-tutorials#26]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Download repository
> Update All Nuget packages
> Build

### Any log messages given by the failure
> 
![image](https://user-images.githubusercontent.com/578882/133755479-9664b701-7095-4266-ad24-6f34fa143926.png)

### Expected/desired behavior
> The samples should build (?)

### OS and Version?
> Windows 10, Visual Studio 2019 fully patched
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by xpouyat** [comment]
Thanks ! I made a PR and it should be approved soon. https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials/pull/27
I recommend you to use samples from this repo : https://github.com/Azure-Samples/media-services-v3-dotnet/ Code is more recent and supports the Media SDK v 5.0.0.0.

**Comment by sumitkm** [comment]
Thanks @xpouyat . 

Can anyone point me to the Documentation that describes `ApiErrorException` is now `ErrorResponseException` ? I genuinely want to keep track of these random breaking changes the Media Services team loves to make.

**Comment by johndeu** [comment]
Approved. Should be working fine now.

**Comment by johndeu** [comment]
@sumitkm  - It was already in the Release notes for a month - https://docs.microsoft.com/en-us/azure/media-services/latest/release-notes 

Unfortunately, it's not simple to subscribe to the Release notes updates. Other than maybe via Github changes.

**Comment by sumitkm** [comment]
Thanks @johndeu . I'll just bookmark the link for now.
