### ISSUE TITLE
Asset name is empty in Azure portal

### ISSUE THREAD

**Issue by danpadmore** [Azure-Samples/media-services-v3-dotnet-tutorials#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the *UploadEncodeAndStreamFiles* sample
> Login to Azure portal
> Go to Assets under Media Services
> Name is empty, Asset Type is unknown, Size is 0 bytes

Note specifying the name and type in the parameters argument, doesn't have any effect either:
```
Asset asset = await client.Assets.CreateOrUpdateAsync(resourceGroupName, accountName, assetName, new Asset(name: assetName, type: "dummy type"));
```

### Any log messages given by the failure
> No errors occur

### Expected/desired behavior
> Name should equal specified input asset name
> Size should reflect video file size

### OS and Version?
> Windows 10

### Versions
>.NET Core 2.1, package Microsoft.Azure.Management.Media 1.0

**Comment by Juliako** [comment]
@danpadmore, Media Services does not yet support v3 Preview in the Azure portal. Use APIs to manage v3 resources. You can see the .NET example here: in https://docs.microsoft.com/en-us/azure/media-services/latest/stream-files-tutorial-with-api

**Comment by k-miyake** [comment]
I could not browse asset even when using Azure Media Services Explorer. Is there plan for Azure Media Services Explorer to support V3?

**Comment by danpadmore** [comment]
@Juliako thanks, I understand now! I read the docs part about v3 not being supported on the portal yet, but the because the assets are visible already I assumed all it's properties should be displayed in full.
