### ISSUE TITLE
How do you authorize requests to stream videos with AES encryption?

### ISSUE THREAD

**Issue by danpadmore** [Azure-Samples/media-services-v3-dotnet-tutorials#6]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> I would like documentation, or a sample on how to perform custom authorization of users that want to stream a video with AES encryption.

I assume you need to:
1. Create a streaming policy with [EnvelopeEncryption ](https://github.com/Azure/azure-sdk-for-net/blob/d422870796b6d4f50697469bd8dc80c9f43fe5e2/src/SDKs/Media/Management.Media/Generated/Models/EnvelopeEncryption.cs)that specifies a [customLicenseAcquisitionUrlTemplate ](https://github.com/Azure/azure-sdk-for-net/blob/d422870796b6d4f50697469bd8dc80c9f43fe5e2/src/SDKs/Media/Management.Media/Generated/Models/EnvelopeEncryption.cs#L83)that points to your own key delivery service
2. Create a streaming locator that uses the above streaming policy
3. When the user's media player then requests a key from your key delivery service, you can authorize the user at this point and response with the key on success

However, I am not sure how to implement this correctly, or whether this is even the way to approach this.

I did try implementing this approach anyway, but I don't know which key to return from the key delivery service.
I assume this should be the AES key that is used to encrypt the video, but I don't know where to get this.

Please advise.

**Comment by danpadmore** [comment]
Related to this issue, I tried creating a StreamingLocator with a StreamingLocatorUserDefinedContentKey.
Because I assume the user defined content key might be the key used to encrypt the video.

But I keep getting a "500 - Internal server error" when creating the StreamingLocator, so I cannot validate this approach.

**Comment by Juliako** [comment]
@danpadmore,
Have you tried using PredefinedStreamingPolicy.ClearKey as shown in the sample?

private static async Task<StreamingLocator> CreateStreamingLocatorAsync(
            IAzureMediaServicesClient client,
            string resourceGroup,
            string accountName,
            string assetName,
            string locatorName,
            string contentPolicyName)
        {
            StreamingLocator locator = await client.StreamingLocators.CreateAsync(
                resourceGroup,
                accountName,
                locatorName,
                new StreamingLocator
                {
                    AssetName = assetName,
                    StreamingPolicyName = PredefinedStreamingPolicy.ClearKey,
                    DefaultContentKeyPolicyName = contentPolicyName
                });

            return locator;
        }

**Comment by Juliako** [comment]
@danpadmore 

The following list gives an overview of three parts you would need to implement for "content protection", in your case AES. 

1. Azure Media Services code
   You can follow the example shown in https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials/tree/master/AMSV3Tutorials/EncryptWithAES  
 
2. Player with AES client. A video player app based on a player SDK (either native or browser-based) 

    You can use this https://ampdemo.azureedge.net/azuremediaplayer.html player to test your AES encrypted content. Make sure you click on "Advanced options" and check AES and provide the token.

3. Secure Token Service (STS), which issues JSON Web Token (JWT) as access token in Media Services key delivery service.

In  https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials/tree/master/AMSV3Tutorials/EncryptWithAES   some test values are used

        private static string Issuer = "myIssuer";
        private static string Audience = "myAudience";

**Comment by danpadmore** [comment]
@Juliako Thank you for looking into this!

Yes, I have tried PredefinedStreamingPolicy.ClearKey, following the EncryptWithAES sample which works perfectly. 
But using that policy I'm not able to specify a customLicenseAcquisitionUrlTemplate, which results in Azure Media Player calling Azure's key delivery service. The goal is to use my own key delivery service, so I can perform authorization to decide whether the user is authorized to view the video (and return the decrption key based on that outcome).
So PredefinedStreamingPolicy.ClearKey is not the way to go in my case, right.

I have thoroughly reviewed the EncryptWithAES sample. The JWT token is processed by Azure's key delivery service, in this case. But this doesn't allow me to perform custom authorization.
The streaming url generated in the EncryptWithAES  sample, can be shared and viewed by anyone who gets the url.

I want to block users from sharing the streaming url. Is a custom key delivery service (via a customLicenseAcquisitionUrlTemplate) the approach for this, or am I coming at it from the wrong angle?

**Comment by Juliako** [comment]
@danpadmore , 
if you want to use custom authorization, you should still use Media Services API for key delivery.

The correct approach is to leverage STS (Secure Token Service):
In STS, depending on user profile, add different claims (such as “Premium User”, “Basic User”, “Free Trial User”). With different claims in a JWT, the user can see different contents. Of course, for different content/asset, the ContentKeyPolicyRestriction will have the corresponding RequiredClaims.

Please, let me know if you have more questions.

**Comment by danpadmore** [comment]
@Juliako Okay, got it!

I was so focused on a custom key delivery service (and the mysterious customLicenseAcquisitionUrlTemplate ;-)), I overlooked the ContentKeyPolicyTokenRestriction is actually good enough.

Thanks for you help.
