### ISSUE TITLE
How to trim a video in v3?

### ISSUE THREAD

**Issue by danpadmore** [Azure-Samples/media-services-v3-dotnet-tutorials#8]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

How can you trim a video in v3?

This is documented in v2 here: https://docs.microsoft.com/en-us/azure/media-services/previous/media-services-advanced-encoding-with-mes#trim_video

However, the [.NET SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.media.models.standardencoderpreset?view=azure-dotnet#properties) or [REST API](https://docs.microsoft.com/en-us/rest/api/media/transforms/createorupdate) does not expose a sources property on a preset in v3.

**Comment by Juliako** [comment]
@danpadmore , this feature is not implemented in v3 yet. It is in the backlog.

**Comment by danpadmore** [comment]
@juliako ok, thank you.

What do you recommend then for new development that's planned to go live this year, v2 or v3?

**Comment by Juliako** [comment]
@danpadmore, since you needs to go live this year, you have to use v2

**Comment by danpadmore** [comment]
@juliako Thanks again for your quick assistance!
